spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: tda-webclient

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml

security:
  app-user:
    name: ${APP_USERNAME}
    password: ${APP_PASSWORD}

server:
  port: 9001

app:
  cors:
    allowed-origin: ${APP_ALLOWED_ORIGINS}